@isTest
public class TestBoosterTest {
    @isTest
    public static void main(){
        TestBooster.testBoosterMethod();
        TestBooster.testBoosterMethod1();
        TestBooster.testBoosterMethod2();
        TestBooster.testBoosterMethod3();
        TestBooster.testBoosterMethod4();
        TestBooster.testBoosterMethod5();
        TestBooster.testBoosterMethod6();
        TestBooster.testBoosterMethod7();
        TestBooster.testBoosterMethod8();
        TestBooster.testBoosterMethod9();
        TestBooster.testBoosterMethod10();
        TestBooster.testBoosterMethod11();
    }
}